### ISSUE TITLE
Should this library provide a blocking interface?

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-asset#82]
Right now, all of our main entrypoint functions are `async`. Should this library provide a blocking interface, e.g. `stac_asset.blocking.download_item`, a la https://docs.rs/reqwest/latest/reqwest/blocking/index.html? Or is it easy enough for a Python API user to make their own blocking version?

**Comment by matthewhanson** [comment]
I'd be +1 for a blocking interface....I think.  The whole library is about making this more convenient for developers since if someone wanted to do downloads themselves for their particular use case it wouldn't be that difficult ... loop through assets and download href.   

A common use case here is to download items then do something with them so this seems useful.

**Comment by ircwaves** [comment]
+1 as well.  A blocking interface would be useful for folks who are less familiar with async functions.
